### PR TITLE
slash before php global functions

### PR DESCRIPTION
**Pull request by jcheron**
as agreed...
To prevent php from searching for the function in the current namespace.
Logically, I only added slashes, so I did not ruin the PSR2 compliance.

### CODE REVIEW

**Comment by aik099** [comment]
Is this PR ready for merging.

P.S.

Because you're sending PR from `master` branch of your fork you're not able to send 2 PR in parallel with different content.

**Comment by jcheron** [comment]
yes, it's ready
I thought that having done a merge before (since php-annotations / master) would be enough...
You want me to do something?

**Comment by aik099** [comment]
It's better to:

1. send each PR from dedicated topic branch (not `master` branch) in your fork
2. squash when ready for merging

**Comment by jcheron** [comment]
I feel that I will make you waste time...
Should I close this PR?

**Comment by aik099** [comment]
I'll try to squash upon merge this one, but next time really (not for this library, but all GitHub PR sending) please send PR from topic branches.

**Comment by aik099** [comment]
Merged, thanks @jcheron .

**Comment by jcheron** [comment]
Understood,
thanks @aik099 !

PS: 
By adding slashes, I saw a suspicious line (to optimize?):
line 349 in **AnnotationParser**
```php
        for ($i = 0; $i < \strlen($str); $i++) {
            $char = \substr($str, $i, 1);
```
Which I shall replace by:
```php
        $len = \strlen($str);
        for ($i = 0; $i < $len; $i++) {
            $char = $str[$i];
```

**Comment by aik099** [comment]
Isn't `$str[$i]` syntax (offset based string symbol access) you're suggesting removed in PHP 7?

If that is the case, then usage of `substr` isn't a mystery anymore.

**Comment by jcheron** [comment]
no, `$str[$i]` syntax still exists in PHP 7
but this is not multi-byte safe.
This is a good reason for using `substr`

see http://php.net/manual/en/language.types.string.php#language.types.string.substr

**Comment by aik099** [comment]
The `substr` isn't multibyte safe, the `mb_substr` is. Anyway I bet `substr` is used for speed and hopes that annotation names would in english or whatever that code fragment does.

**Comment by jcheron** [comment]
It is not very serious, the difference being less.
But `$str[$i]` is faster by 20% than `substr($str, $i, 1)`

Average over 1000000 iterations:
- substr($str,$i,1) : 7.5790905952454E-7
- $str[$i] : 5.960099697113E-7

and the call of `strlen($str)` should not be in the `for`, to avoid it being called at each iteration.

**Comment by aik099** [comment]
OK, this is worth sending another PR.

In general if we look at https://github.com/php-annotations/php-annotations/blame/master/src/annotations/AnnotationParser.php#L349-L350 one more thing can be optimized: moving out `\strlen(` call outside of for. I guess length of parsed string isn't changed during parsing, but we're doing `strlen` call for each symbol in parsed file. That can result in slowdown on initial parsing until results of parsing are cached.

**Pull request merged**
