### PR TITLE
Ignore static analisis annotations (phpstan, psalm, codeCoverage)

### PR DESCRIPTION
**Pull request by dimtrovich**
when trying to read the annotation of a property (or method/class), if among these annotations there is an annotation not taken into account in `AnnotationManager::registry` (such as @phpstan-ignore -line) an exception is thrown. However, static analysis annotations and code coverage have been recurrent in recent years.

### CODE REVIEW

**Review by aik099 — APPROVED** [review]

**Comment by aik099** [comment]
Looks good.

**Comment by aik099** [comment]
@dimtrovich you've requested my review, but I have not seen any changes since I approved your PR.

**Comment by dimtrovich** [comment]
@aik099 in fact, I did a `composer update` and the modifications had not been taken into account so I was wondering if it was possible to do a merge and a release for these modifications to be effective

as for me, I made a patch for that 😅. But it's not a long term solution.

**Comment by aik099** [comment]
Merging, thanks @dimtrovich .

**Comment by aik099** [comment]
Released as 1.3.3.

**Pull request merged**
